##==MemoryManagement=========
max_number_of_octs 1000000
max_number_of_part 1000000
mpi_buffer_size 800000
##==TimestepManagement=======
output_frequency 50
max_nuber_of_steps 500
time_step_max  1e0
tmax_or_amax 10000.
##==AMRGrid==================
level_coarse 7
level_max 8
amr_thresh 0.015
n_smooth 2
##==PoissonSolver============
max_number_of_relaxation_poisson 1000
poisson_accuracy 1e-2
mgrid_lmin 3
mgrid_nvcycles 3
mgrid_nsmooth 5
##==Restart==================
restart_snap 0
##==ThreadManagement======
grav_stencil_size 32
cons_stencil_size 32
max_subcycles 2
nthread 16
nstream 16
##==RadTransfert======
clight 1e-1
dens_threshold 0.5
temp_threshold 1e5
src_int 0
##==StarFormation============
overdensity_cond 150
density_cond -500
tcar 2e9
tlife 2e5
feedback_eff 1.
feedback_frac 1.
##==Movie====================
lmap 7
xmin 0
xmax 1
ymin 0
ymax 1
zmin 0
zmax 1
