##==MemoryManagement=========
max_number_of_octs 3000000
max_number_of_part 3000000
mpi_buffer_size 500000
##==TimestepManagement=======
output_frequency 10
max_nuber_of_steps 500
time_step_max  1e-0
tmax_or_amax 1000.0
##==AMRGrid==================
level_coarse 6
level_max 8
amr_thresh 5e-7
n_smooth 8
##==PoissonSolver============
max_number_of_relaxation_poisson 100
poisson_accuracy 1e-3
mgrid_lmin 4
mgrid_nvcycles 3
mgrid_nsmooth 5
##==Restart==================
restart_snap 0
##==ThreadManagement======
grav_stencil_size 32
cons_stencil_size 32
max_subcycles 2
nthread 16
nstream 16
##==RadTransfert======
clight 1e-2
dens_threshold 0.5
temp_threshold 1e5
src_int 5e56
