##==MemoryManagement=========
max_number_of_octs 500000
max_number_of_part 3000000
mpi_buffer_size 500000
##==TimestepManagement=======
output_frequency   1000
max_nuber_of_steps 0
time_step_max  1e-0
tmax_or_amax 0.5 
##==AMRGrid==================
level_coarse 6
level_max 6
amr_thresh 8
n_smooth 2
##==PoissonSolver============
max_number_of_relaxation_poisson 1000
poisson_accuracy 1e-3
mgrid_lmin 4
mgrid_nvcycles 3
mgrid_nsmooth 5
##==Restart==================
restart_snap 0
##==ThreadManagement======
grav_stencil_dl 2
grav_stencil_size 1
cons_stencil_size 16
max_subcycles 2
nthread 16
nstream 16
ompthreads 4
##==RadTransfert======
clight 1e-3
dens_threshold 5e20 
src_int 1e20
temp_threshold 1e5
##==StarFormation=========
overdensity_cond 5
density_cond -500
tcar 9e9
tlife 3e7
feedback_eff 1
feedback_frac 1.
