##==MemoryManagement=========
max_number_of_octs 600000
max_number_of_part 3000000
mpi_buffer_size 18000
##==TimestepManagement=======
output_frequency 50
max_nuber_of_steps 52
time_step_max  1.0
##==AMRGrid==================
level_coarse 7
level_max 7
amr_thresh 4e-6
##==PoissonSolver============
max_number_of_relaxation_poisson 100
poisson_accuracy 1e-3
mgrid_lmin 3
mgrid_nvcycles 3
mgrid_nsmooth 5
##==Restart==================
restart_snap 0
##==ThreadManagement======
grav_stencil_size 16
cons_stencil_size 16
max_subcycles 2
nthread 128
nstream 2
##==RadTransfert======
clight 1e-2
src_threshold 1.5
src_int 5e48
