##==MemoryManagement=========
max_number_of_octs 500000
max_number_of_part 1000000
mpi_buffer_size 500000
##==TimestepManagement=======
output_frequency 250
max_nuber_of_steps 9000
time_step_max  1e0
tmax_or_amax 0.15
##==AMRGrid==================
level_coarse 6
level_max 10
amr_thresh 8
n_smooth 2
##==PoissonSolver============
max_number_of_relaxation_poisson 100
poisson_accuracy 1e-3
mgrid_lmin 3
mgrid_nvcycles 3
mgrid_nsmooth 5
##==Restart==================
restart_snap 0
##==ThreadManagement======
grav_stencil_size 16
cons_stencil_size 16
max_subcycles 2
nthread 16
nstream 1
ompthreads 1
##==RadTransfert============
clight 1e-1
dens_threshold 5e20
temp_threshold 1e5
src_int 1e15
##==StarFormation============
overdensity_cond 500
density_cond -500
tcar 4e9
tlife 2e7
##==SuperNovae===============
feedback_eff 1.
feedback_frac 1.
##==Movie====================
lmap 9
xmin 0
xmax 1
ymin 0
ymax 1
zmin 0
zmax 1
