##==MemoryManagement=========
max_number_of_octs 300000
max_number_of_part 3000000
mpi_buffer_size 500000
##==TimestepManagement=======
output_frequency 100
max_nuber_of_steps 1000000
time_step_max  1e0
tmax_or_amax 0.15
##==AMRGrid==================
level_coarse 7
level_max 25
amr_thresh 8
n_smooth 2
##==PoissonSolver============
max_number_of_relaxation_poisson 10
poisson_accuracy 1e-3
mgrid_lmin 4
mgrid_nvcycles 3
mgrid_nsmooth 5
##==Restart==================
restart_snap 0
##==ThreadManagement======
grav_stencil_size 16
cons_stencil_size 16
max_subcycles 2
nthread 16
nstream 1
ompthreads 1
##==RadTransfert======
clight 1e-1
dens_threshold 5e20
temp_threshold 1e5
src_int 1e60
##==StarFormation=========
overdensity_cond 5
density_cond -500
tcar 3e9   
tlife 2e7
feedback_eff 0
feedback_frac 1.
