##==MemoryManagement=========
max_number_of_octs 250000
max_number_of_part 262144
mpi_buffer_size 131072
##==TimestepManagement=======
output_frequency 1
max_number_of_steps 100
time_step_max  1e0
##==AMRGrid==================
level_coarse 5
level_max 7
amr_thresh 0.00003
##==PoissonSolver============
max_number_of_relaxation_poisson 100
poisson_accuracy 1e-3
mgrid_lmin 2
mgrid_nvcycles 3
mgrid_nsmooth 10
##==Restart==================
restart_snap 0
##==ThreadManagement======
vector_stencil_size 32768
max_subcycles 2
nthread 128
nstream 1
##==RadTransfert======
clight 0.001
src_threshold 0.45
src_int 1e60
