##==MemoryManagement=========
max_number_of_octs 100000
max_number_of_part 100000
mpi_buffer_size 800000
##==TimestepManagement=======
output_frequency 200
max_nuber_of_steps 30000
time_step_max  1e2
tmax_or_amax 10000.
##==AMRGrid==================
level_coarse 5
level_max 8
amr_thresh 0.5
n_smooth 2
##==PoissonSolver============
max_number_of_relaxation_poisson 1000
poisson_accuracy 1e-2
mgrid_lmin 3
mgrid_nvcycles 3
mgrid_nsmooth 5
##==Restart==================
restart_snap 0
##==ThreadManagement======
grav_stencil_size 32
cons_stencil_size 32
max_subcycles 2
nthread 16
nstream 16
##==RadTransfert======
clight 1e-1
dens_threshold 0.5
temp_threshold 1e5
src_int 5e48
