##==MemoryManagement=========
max_number_of_octs 50000
max_number_of_part 5
mpi_buffer_size 131072
##==TimestepManagement=======
output_frequency 1
max_number_of_steps 1000
time_step_max  1e-3
##==AMRGrid==================
level_coarse 6
level_max 6
amr_thresh 0.1
##==PoissonSolver============
max_number_of_relaxation_poisson 100
poisson_accuracy 1e-3
mgrid_lmin 2
mgrid_nvcycles 3
mgrid_nsmooth 10
##==Restart==================
restart_snap 0
##==ThreadManagement======
vector_stencil_size 16
max_subcycles 2
nthread 64
nstream 4
