#!/usr/bin/env python
import os, sys
from shutil import copyfile

MKFOLDER="./mk/"

def launch():
	os.chdir(FOLDER)
	script_type = get_script_type()
	os.system("%s%s"%(script_type, RUN_NAME))

def head(name):
	print()
	print("###############################################################")
	print("###############################################################")
	print("%s"%name)
	print("###############################################################")
	print("###############################################################")
	print()

if __name__ == "__main__":

	tests=[
		"test_grid",
		"test_grafic_ic",
		"test_uniform_grid",
		"test_star_formation",
		]

	for test in tests:

		head(test)

		copyfile("mk/%s.mk"%(test), "test.mk")

		status = os.system("make clean && make")
		if status != 0 :
			sys.exit()

		status = os.system("./test")
		if status != 0 :
			sys.exit()



	mpi_tests=[
		["test_mpi",4],
		["test_grid_mpi",4],
		["test_sedov_mpi",4],
		]

	for test in mpi_tests:
		head(test[0])

		copyfile("mk/%s.mk"%(test[0]), "test.mk")

		status = os.system("make clean && make -j %d"%(test[1]))
		if status != 0 :
			sys.exit()

		status = os.system("mpiexec -np %d ./test"%(test[1]))
		if status != 0 :
			sys.exit()
