##==MemoryManagement=========
max_number_of_octs 400000
max_number_of_part 3000000
mpi_buffer_size 50000
##==TimestepManagement=======
output_frequency 10
dt_dump 0
max_nuber_of_steps 400
time_step_max  1e0
tmax_or_amax 0.15
##==AMRGrid==================
level_coarse 6
level_max 6
amr_thresh 8
n_smooth 2
##==DM=======================
dm_res 0
dx_res 1e2
##==PoissonSolver============
max_number_of_relaxation_poisson 100
poisson_accuracy 1e-3
mgrid_lmin 4
mgrid_nvcycles 3
mgrid_nsmooth 5
##==Restart==================
restart_snap 0
##==ThreadManagement======
grav_stencil_size 16
cons_stencil_size 16
max_subcycles 2
nthread 16
nstream 1
ompthreads 1
##==RadTransfert============
clight 1e-1
dens_threshold 5e20
temp_threshold 1e5
src_int_or_fesc 0e16
##==StarFormation============
overdensity_cond 150
density_cond -500
efficiency 0.01
tlife 10e6
mass_res 2
##==SuperNovae===============
feedback_eff 0.
feedback_frac 1.0
##==Movie====================
lmap 9
xmin 0
xmax 1
ymin 0
ymax 1
zmin 0
zmax 1
